### PR TITLE
Updated redis dependency

### PR DESCRIPTION
**Pull request by mrbatista**

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by superkhau** [comment]
I'm don't think we can just upgrade the underlying lib without ensuring we're not breaking what's currently there. I'm going to renable the test to make sure this can be landed safely (right now all tests are being skipped so thats why you see full green on CI).

**Comment by raymondfeng** [comment]
redis dep is upgraded.

**Pull request closed without merging**
